import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import { style } from '@mui/system';
import Link from 'next/link'

export default function Contact() {
    return (
        <div>
            <Head>
                <title>RPGaming Fest</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid container>
                <Grid item xs={4} style={{ width: '100%', height: '1600px', background: '#16166e', display: 'flex', justifyContent: 'flex-end' }}>
                    <div style={{ margin: 50, position: 'fixed', backgroundColor: '' }}>
                        <Image src="/logoAsso.png" alt="logo association RPGaming Fest" width={100} height={100} />
                        <h2 style={{ textAlign: 'end', color: 'white', marginBottom: 50, fontSize: 35 }}>RPGaming Fest</h2>
                        <div style={{ display: 'flex', flexDirection: 'column', color: 'white' }}>
                            <span style={{ fontSize: 22, fontWeight: 700, marginBottom: 20, fontSize: 30, textAlign: 'end' }}>Edition 2023</span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/">Accueil</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/programme">Programme</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}>Plan du site</span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/contact">Contact</Link></span>
                        </div>
                    </div>
                </Grid>
                <Grid item xs={8} style={{ width: '100%', height: '100px' }}>
                    <Box style={{ margin: 70 }}>
                        <div style={{ marginBottom: 20, fontSize: 20 }}>Une question ? conactez-nous grâce à notre formulaire de contact</div>
                        <div>
                            <TextField
                                label="Prénom"
                                variant="outlined"
                                style={{ margin: 10, width: 200 }}
                                InputLabelProps={{
                                    shrink: true,
                                }}
                            />
                            <TextField
                                label="Nom"
                                variant="outlined"
                                style={{ margin: 10, width: 200 }}
                                InputLabelProps={{
                                    shrink: true,
                                }}
                            />
                        </div>
                        <div>
                            <TextField
                                label="Mail"
                                variant="outlined"
                                style={{ margin: 10, width: 350 }}
                                InputLabelProps={{
                                    shrink: true,
                                }}
                            />
                        </div>
                        <div>
                            <TextField
                                label="Votre message"
                                variant="outlined"
                                multiline
                                rows={4}
                                style={{ margin: 10, width: 420 }}
                                InputLabelProps={{
                                    shrink: true,
                                }}
                            />
                        </div>
                        <div>
                            <Button variant="outlined" style={{margin: 10}}>Envoyer</Button>
                        </div>
                    </Box>
                </Grid>
            </Grid>

            {/* <footer className={styles.footer}>
        <p>Conçu par Dyme agency</p>
      </footer> */}
        </div>
    )
}
