import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import { style } from '@mui/system';
import Link from 'next/link'
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';

export default function Home() {
  return (
    <div>
      <Head>
        <title>RPGaming Fest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container>
        <Grid item xs={4}  style={{ width: '100%', height: '100vh', background: '#D73C36', display: 'flex', justifyContent: 'flex-end' }}>
          <div className={styles.leftPart} style={{ position: 'fixed', backgroundColor: '#D73C36', width: '100%', height: '100vh' }}>
            <div style={{ width: '100%', height: '120px', backgroundColor: 'white', marginTop: 70, color: 'black' }}>
              <span style={{ backgroundColor: 'white', marginLeft: 50 }}>
                <Image src="/logoAsso.png" alt="logo association RPGaming Fest" width={100} height={100} />
              </span>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', color: 'white', marginRight: 50 }}>
              <span style={{ fontSize: 22, fontWeight: 700, marginBottom: 20, fontSize: 30, textAlign: 'end' }}>Edition 2023</span>
              <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/">Accueil</Link></span>
              <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/programme">Programme</Link></span>
              <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/plan-du-site">Plan du site</Link></span>
              <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/contact">Contact</Link></span>
            </div>
          </div>
        </Grid>
        <Grid item xs={8} style={{ width: '100%', height: '100px' }}>
          <Box style={{ margin: 70 }}>
            <h1 id="accueil" style={{ color: '#16166e' }}>RPGaming Fest</h1>
            <p style={{ fontSize: 18, color: 'rgba(0,0,0,0.8)', marginBottom: 70 }}>La RPGaming Fest se déroulera les samedi 21 et dimanche 22 janvier au parc des expositions de Rouen.</p>
            <div className={styles.boxShadow1} style={{ display: 'flex', borderRadius: 25, border: '1px solid rgba(0,0,0,0.1)' }}>
              <Image src="/Aurmidh.png" width={300} height={300} />
              <div style={{ display: 'flex', alignItems: 'center', margin: 20 }}>
                <div style={{ background: '' }}>
                  <div>
                    <h2 style={{ display: 'flex', justifyContent: 'center', color: '#D73C36', fontSize: 25 }}>8 tables de jeux plus une ludothèque</h2>
                  </div>
                  <p style={{ fontWeight: 500, marginTop: 40, textAlign: 'justify', fontFamily: "font", fontSize: 21, lineHeight: 1.7, color: 'rgba(0,0,0,0.8)' }}>Une ludothèque et des espaces thématiques seront à votre disposition pour permettre de jouer une ou plusieurs parties de vos jeux favoris ou de pépites encore inconnues (Zombicide, Saboteur, Dungeons & Dragons, Civis, et pleins d’autres…)</p>
                </div>
              </div>
            </div>

            <div className={styles.boxShadow1} style={{ display: 'flex', borderRadius: 25, border: '1px solid rgba(0,0,0,0.1)', marginTop: 50 }}>
              <div style={{ display: 'flex', alignItems: 'center', margin: 20 }}>
                <div style={{ background: '' }}>
                  <div>
                    <h2 style={{ display: 'flex', justifyContent: 'center', color: '#D73C36', fontSize: 25 }}>De nombreux exposants présent sur place</h2>
                  </div>
                  <p style={{ fontWeight: 500, marginTop: 40, textAlign: 'justify', fontFamily: "font", fontSize: 21, lineHeight: 1.7, color: 'rgba(0,0,0,0.8)' }}>De nombreux exposants seront présents pour présenter leurs produits et services (dans la limite des stocks disponibles). Différentes conférences auront lieu durant toute la durée de l’événement et des ateliers inviteront petits et grands à créer leur premier jeu de rôle.</p>
                </div>
              </div>
              <Image src="/image1.png" width={300} height={300} />
            </div>

            <div className={styles.boxShadow1} style={{ width: '100%', paddingLeft: 30, paddingRight: 30, paddingTop: 10, paddingBottom: 30, marginTop: 50, borderRadius: 10 }}>
              <p style={{ fontSize: 20, fontWeight: 500, color: 'rgba(0,0,0,0.72)' }}>Renseignez votre email pour recevoir les news de RPGaming Fest</p>
              <div style={{ display: 'flex' }}>
                <div style={{ width: '70%' }}>
                  <TextField
                    label="Newsletter"
                    size="small"
                    fullWidth
                  />
                </div>
                <div style={{ width: '25%', marginLeft: '2%' }}>
                  <Button variant="contained" style={{ fontWeight: 600 }} >
                    {"S'inscrire"}
                  </Button>
                </div>
              </div>
            </div>
            <div style={{ textAlign: 'center', marginTop: 10 }}>Suivez nous sur Twitter, Facebook ou Linkedin pour connaître rapidement toutes les news.</div>
            <div style={{ marginTop: 100 }}>
              <p style={{ fontWeight: 600, fontSize: 20 }}>Sponsors 2023: 6 sponsors</p>
              <Grid container spacing={2}>
                <Grid item xs={12} sm={6} md={4} className={styles.cardImg}>
                  <span style={{ backgroundColor: '' , border: '1px solid rgba(0,0,0,0.2)', borderRadius: 10,}}>
                    <Image src="/Aurmidh.png" width={200} height={200} />
                  </span>
                </Grid>
                <Grid item xs={12} sm={6} md={4} className={styles.cardImg}>
                  <span style={{ backgroundColor: '' , border: '1px solid rgba(0,0,0,0.2)', borderRadius: 10, }}>
                    <Image src="/img2.png" width={200} height={200} />
                  </span>
                </Grid>
                <Grid item xs={12} sm={6} md={4} className={styles.cardImg}>
                  <span style={{ backgroundColor: '' , border: '1px solid rgba(0,0,0,0.2)', borderRadius: 10, }}>
                    <Image src="/img3.png" width={200} height={200} />
                  </span>
                </Grid>
                <Grid item xs={12} sm={6} md={4} className={styles.cardImg}>
                  <span style={{ backgroundColor: '' , border: '1px solid rgba(0,0,0,0.2)', borderRadius: 10, }}>
                    <Image src="/img4.png" width={200} height={200} />
                  </span>
                </Grid>
                <Grid item xs={12} sm={6} md={4} className={styles.cardImg}>
                  <span style={{ backgroundColor: '' , border: '1px solid rgba(0,0,0,0.2)', borderRadius: 10, }}>
                    <Image src="/img5.png" width={200} height={200} />
                  </span>
                </Grid>
                <Grid item xs={12} sm={6} md={4} className={styles.cardImg}>
                  <span style={{ backgroundColor: '' , border: '1px solid rgba(0,0,0,0.2)', borderRadius: 10, }}>
                    <Image src="/img6.png" width={200} height={200} />
                  </span>
                </Grid>
              </Grid>
            </div>
          </Box>
        </Grid>
      </Grid>
      {/* <footer className={styles.footer}>
        <p>Conçu par Dyme agency</p>
      </footer> */}
    </div>
  )
}
