import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import { style } from '@mui/system';
import Link from 'next/link'
import localFont from '@next/font/local';

const titleFont = localFont({ src: '../public/fonts/enchanted_land-webfont.woff' })

export default function Plandusite() {
    return (
        <div>
            <Head>
                <title>RPGaming Fest</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid container>
                <div className={styles.menuMobile}>
                    <img src="logoAsso2.png" width='80px' style={{ marginLeft: '2vw' }} />
                    <div className={titleFont.className} style={{ display: 'flex', justifyContent: 'space-between', width: '100%', alignItems: 'center', marginLeft: '2vw', marginRight: '2vw', fontWeight: 500, color: '#D73C36', fontSize: '3.5vw', fontSize: '24px' }}>
                        <span><Link href="/">Accueil</Link></span>
                        <span><Link href="/programme">Programme</Link></span>
                        <span><Link href="/plan-du-site">Plan du site</Link></span>
                        <span><Link href="/contact">Contact</Link></span>
                    </div>
                </div>
                <Grid className={styles.menuPC} item md={4} xs={0}>
                    <div className={styles.leftPart} style={{ position: 'fixed', backgroundColor: '#D73C36', width: '100%', height: '100vh' }}>
                        <div className={titleFont.className} style={{ display: 'flex', flexDirection: 'column', color: 'white', marginRight: 50 }}>
                            <span style={{ marginBottom: -35, fontWeight: 500, fontSize: 25, textAlign: 'end', marginRight: -40 }}><img src="/logoBlanc.png" style={{ width: '150px' }} /></span>
                            <span style={{ fontWeight: 700, marginBottom: 20, fontSize: 38, textAlign: 'end' }}>Première édition</span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 32, textAlign: 'end' }}><Link href="/">Accueil</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 32, textAlign: 'end' }}><Link href="/programme">Programme</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 32, textAlign: 'end' }}><Link href="/plan-du-site">Plan du site</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 32, textAlign: 'end' }}><Link href="/contact">Contact</Link></span>
                        </div>
                    </div>
                </Grid>
                <Grid item md={8} xs={12} style={{ width: '100%', height: '100px' }}>
                    <Box style={{ margin: '4vw' }}>
                        <div style={{ marginTop: 70 }}>
                            <h2 id="plan-du-site" className={titleFont.className} style={{ display: 'flex', color: '', fontSize: 36 }}>Plan du site</h2>
                            <img src="/plan2.jpg" alt="Plan du site" width={'100%'} />
                            <img src="/accesParc.png" alt="Accès au parc d'exposition" width={"80%"} style={{marginLeft: '10%', marginTop: '30px'}} />
                        </div>
                    </Box>
                </Grid>
            </Grid>
        </div>
    )
}
