import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import { style } from '@mui/system';
import Link from 'next/link'

export default function Plandusite() {
    return (
        <div>
            <Head>
                <title>RPGaming Fest</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid container>
                <Grid className={styles.menuPC} item md={4} xs={0}>
                    <div className={styles.leftPart} style={{ position: 'fixed', backgroundColor: '#D73C36', width: '100%', height: '100vh' }}>
                        <div style={{ width: '100%', height: '120px', backgroundColor: 'white', marginTop: 70, color: 'black' }}>
                            <span style={{ backgroundColor: 'white', marginLeft: 50 }}>
                                <Image src="/logoAsso.png" alt="logo association RPGaming Fest" width={100} height={100} />
                            </span>
                        </div>
                        <div style={{ display: 'flex', flexDirection: 'column', color: 'white', marginRight: 50 }}>
                            <span style={{ fontSize: 22, fontWeight: 700, marginBottom: 20, fontSize: 30, textAlign: 'end' }}>Edition 2023</span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/">Accueil</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/programme">Programme</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/plan-du-site">Plan du site</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/contact">Contact</Link></span>
                        </div>
                    </div>
                </Grid>
                <Grid item md={8} xs={12} style={{ width: '100%', height: '100px' }}>
                    <Box style={{ margin: 70 }}>
                        <div style={{ marginTop: 70 }}>
                            <h2 id="plan-du-site" style={{ display: 'flex', color: '', fontSize: 28 }}>Plan du site</h2>
                            <img src="/plan2.jpg" alt="Plan du site" width={'100%'} />
                        </div>
                    </Box>
                </Grid>
            </Grid>

            {/* <footer className={styles.footer}>
        <p>Conçu par Dyme agency</p>
      </footer> */}
        </div>
    )
}
