import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import { style } from '@mui/system';
import Link from 'next/link'

export default function Plandusite() {
    return (
        <div>
            <Head>
                <title>RPGaming Fest</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid container>
                <Grid item xs={4} style={{ width: '100%', height: '1600px', background: '#16166e', display: 'flex', justifyContent: 'flex-end' }}>
                    <div style={{ margin: 50, position: 'fixed', backgroundColor: '' }}>
                        <Image src="/logoAsso.png" alt="logo association RPGaming Fest" width={100} height={100} />
                        <h2 style={{ textAlign: 'end', color: 'white', marginBottom: 50, fontSize: 35 }}>RPGaming Fest</h2>
                        <div style={{ display: 'flex', flexDirection: 'column', color: 'white' }}>
                            <span style={{ fontSize: 22, fontWeight: 700, marginBottom: 20, fontSize: 30, textAlign: 'end' }}>Edition 2023</span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/">Accueil</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/programme">Programme</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}>Plan du site</span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/contact">Contact</Link></span>
                        </div>
                    </div>
                </Grid>
                <Grid item xs={8} style={{ width: '100%', height: '100px' }}>
                    <Box style={{ margin: 70 }}>
                        <div style={{ marginTop: 70 }}>
                            <h2 id="plan-du-site" style={{ display: 'flex', justifyContent: 'center', marginBottom: -50, color: '#16166e', fontSize: 25 }}>Plan du site</h2>
                            <div style={{ display: 'flex', justifyContent: 'center', marginTop: 50 }}>
                                <Image src="/plan.jpg" alt="Plan du site" width={800} height={600} />
                            </div>
                        </div>
                    </Box>
                </Grid>
            </Grid>

            {/* <footer className={styles.footer}>
        <p>Conçu par Dyme agency</p>
      </footer> */}
        </div>
    )
}
