import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import { style } from '@mui/system';
import Link from 'next/link'

export default function Programme() {
    return (
        <div>
            <Head>
                <title>RPGaming Fest</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid container>
                <Grid item xs={4} style={{ width: '100%', height: '100vh', background: '#D73C36', display: 'flex', justifyContent: 'flex-end' }}>
                    <div className={styles.leftPart} style={{ position: 'fixed', backgroundColor: '#D73C36', width: '100%', height: '100vh' }}>
                        <div style={{ width: '100%', height: '120px', backgroundColor: 'white', marginTop: 70, color: 'black' }}>
                            <span style={{ backgroundColor: 'white', marginLeft: 50 }}>
                                <Image src="/logoAsso.png" alt="logo association RPGaming Fest" width={100} height={100} />
                            </span>
                        </div>

                        <div style={{ display: 'flex', flexDirection: 'column', color: 'white', marginRight: 50 }}>
                            <span style={{ fontSize: 22, fontWeight: 700, marginBottom: 20, fontSize: 30, textAlign: 'end' }}>Edition 2023</span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/">Accueil</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/programme">Programme</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/plan-du-site">Plan du site</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 25, textAlign: 'end' }}><Link href="/contact">Contact</Link></span>
                        </div>
                    </div>
                </Grid>
                <Grid item xs={8} style={{ width: '100%', height: '100px' }}>
                    <Box style={{ margin: 70 }}>
                        <h2 style={{ fontSize: 28 }}>Programme</h2>
                        <p style={{ marginBottom: 50 }}>Cette année, rendez-vous les samedi 21 et dimanche 22 janvier au parc des expositions à Rouen. Ouverture des portes à 8h00.</p>
                        <div style={{ display: 'flex', marginBottom: 20 }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>08:45</div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                        </div>
                        <div style={{ display: 'flex', marginBottom: 20 }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>09:00</div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                        </div>
                        <div style={{ display: 'flex', marginBottom: 20 }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>11:30</div>
                            <div className={styles.cardProgram}>
                                <h3>Pause</h3>
                                <p>Boire un coup, papoter, visiter les stands</p>
                            </div>
                        </div>
                        <div style={{ display: 'flex', marginBottom: 20 }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>11:45</div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                        </div>
                        <div style={{ display: 'flex', marginBottom: 20 }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>12:30</div>
                            <div className={styles.cardProgram}>
                                <h3>Pause repas</h3>
                                <p>Boire un coup, papoter, visiter les stands</p>
                            </div>
                        </div>
                        <div style={{ display: 'flex', marginBottom: 20 }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>13:30</div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                        </div>
                        <div style={{ display: 'flex', marginBottom: 20 }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>15:00</div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                            <div className={styles.cardProgram}>
                                <h3>lorem ispum</h3>
                                <p>lorem ispum lorem ipsum</p>
                            </div>
                        </div>
                    </Box>
                </Grid>
            </Grid>

            {/* <footer className={styles.footer}>
        <p>Conçu par Dyme agency</p>
      </footer> */}
        </div>
    )
}
