import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import { style } from '@mui/system';
import Link from 'next/link'
import localFont from '@next/font/local';

const titleFont = localFont({ src: '../public/fonts/enchanted_land-webfont.woff' })

export default function Programme() {
    return (
        <div>
            <Head>
                <title>RPGaming Fest</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid container>
                <div className={styles.menuMobile}>
                <Link href="/"><img src="logoAsso2.png" width='80px' style={{ marginLeft: '2vw' }} /></Link>
                    <div className={titleFont.className} style={{ display: 'flex', justifyContent: 'space-between', width: '100%', alignItems: 'center', marginLeft: '2vw', marginRight: '2vw', fontWeight: 500, color: '#D73C36', fontSize: '3.5vw', fontSize: '24px' }}>
                        <span><Link href="/">Accueil</Link></span>
                        <span><Link href="/programme">Programme</Link></span>
                        <span><Link href="/plan-du-site">Plan du site</Link></span>
                        <span><Link href="/contact">Contact</Link></span>
                    </div>
                </div>
                <Grid className={styles.menuPC} item md={4} xs={0}>
                    <div className={styles.leftPart} style={{ position: 'fixed', backgroundColor: '#D73C36', width: '100%', height: '100vh' }}>
                        <div className={titleFont.className} style={{ display: 'flex', flexDirection: 'column', color: 'white', marginRight: 50 }}>
                            <span style={{ marginBottom: -35, fontWeight: 500, fontSize: 25, textAlign: 'end', marginRight: -40 }}><img src="/logoBlanc.png" style={{ width: '150px' }} /></span>
                            <span style={{ fontWeight: 700, marginBottom: 20, fontSize: 38, textAlign: 'end' }}>Première édition</span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 32, textAlign: 'end' }}><Link href="/">Accueil</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 32, textAlign: 'end' }}><Link href="/programme">Programme</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 32, textAlign: 'end' }}><Link href="/plan-du-site">Plan du site</Link></span>
                            <span style={{ marginBottom: 15, fontWeight: 500, fontSize: 32, textAlign: 'end' }}><Link href="/contact">Contact</Link></span>
                        </div>
                    </div>
                </Grid>
                <Grid item md={8} xs={12}  >
                    <Box style={{ margin: '4vw' }}>
                        <h2 className={titleFont.className} style={{ fontSize: 36 }}>Programme</h2>
                        <p style={{ marginBottom: 50 }}>Cette année, rendez-vous les samedi 21 et dimanche 22 janvier au parc des expositions à Rouen.</p>
                        <div style={{ display: 'flex' }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>08:45</div>
                            <div className={styles.cardHorizontalProgram}>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                            </div>
                        </div>
                        <div style={{ display: 'flex' }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>09:00</div>
                            <div className={styles.cardHorizontalProgram}>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                            </div>
                        </div>
                        <div style={{ display: 'flex' }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>11:30</div>
                            <div className={styles.cardHorizontalProgram}>
                                <div className={styles.cardProgram}>
                                    <h3>Pause</h3>
                                    <p>Boire un coup, papoter, visiter les stands</p>
                                </div>
                            </div>
                        </div>
                        <div style={{ display: 'flex' }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>11:45</div>
                            <div className={styles.cardHorizontalProgram}>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                            </div>
                        </div>
                        <div style={{ display: 'flex' }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>12:30</div>
                            <div className={styles.cardHorizontalProgram}>
                                <div className={styles.cardProgram}>
                                    <h3>Pause repas</h3>
                                    <p>Boire un coup, papoter, visiter les stands</p>
                                </div>
                            </div>
                        </div>
                        <div style={{ display: 'flex' }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>13:30</div>
                            <div className={styles.cardHorizontalProgram}>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                            </div>
                        </div>
                        <div style={{ display: 'flex' }}>
                            <div style={{ marginRight: 20, marginTop: 20, fontSize: 20, color: 'rgba(0,0,0,0.55)', fontWeight: 600 }}>15:00</div>
                            <div className={styles.cardHorizontalProgram}>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                                <div className={styles.cardProgram}>
                                    <h3>lorem ispum</h3>
                                    <p>lorem ispum lorem ipsum</p>
                                </div>
                            </div>
                        </div>
                    </Box>
                </Grid>
            </Grid>

            {/* <footer className={styles.footer}>
        <p>Conçu par Dyme agency</p>
      </footer> */}
        </div>
    )
}
